# Generated by Django 6.0.6 on 2026-06-16 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActeEtatCivil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_acte', models.CharField(max_length=100, unique=True)),
                ('type_acte', models.CharField(choices=[('NAISSANCE', 'Naissance'), ('MARIAGE', 'Mariage'), ('DECES', 'Décès')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentreEtatCivil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('numero_identification', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('FRAUDE', 'Fraude'), ('DOUBLON', 'Doublon')], max_length=20)),
                ('message', models.TextField()),
                ('niveau_severite', models.IntegerField(default=1)),
                ('est_resolue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalements.acteetatcivil')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte_ocr', models.TextField()),
                ('donnees_extraites', models.JSONField()),
                ('score_fraude', models.IntegerField(default=0)),
                ('score_doublon', models.FloatField(default=0)),
                ('niveau_risque', models.CharField(max_length=20)),
                ('modele_utilise', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signalements.acteetatcivil')),
            ],
        ),
        migrations.AddField(
            model_name='acteetatcivil',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalements.centreetatcivil'),
        ),
        migrations.AddField(
            model_name='acteetatcivil',
            name='citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalements.citoyen'),
        ),
        migrations.AddField(
            model_name='centreetatcivil',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centres', to='signalements.commune'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('hash_document', models.CharField(max_length=255, unique=True)),
                ('qualite_scan', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signalements.acteetatcivil')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='signalements.region'),
        ),
        migrations.AddField(
            model_name='centreetatcivil',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centres', to='signalements.region'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('nom', 'region')},
        ),
        migrations.AddIndex(
            model_name='centreetatcivil',
            index=models.Index(fields=['region', 'commune'], name='signalement_region__001fae_idx'),
        ),
    ]
