# Generated by Django 6.0.6 on 2026-06-16 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signalements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acteetatcivil',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='acte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalements.acteetatcivil'),
        ),
        migrations.AddField(
            model_name='analyseia',
            name='acte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signalements.acteetatcivil'),
        ),
        migrations.AddField(
            model_name='acteetatcivil',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes', to='signalements.centreetatcivil'),
        ),
        migrations.AddField(
            model_name='acteetatcivil',
            name='citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='signalements.citoyen'),
        ),
        migrations.AddField(
            model_name='centreetatcivil',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centres', to='signalements.commune'),
        ),
        migrations.AddField(
            model_name='document',
            name='acte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signalements.acteetatcivil'),
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='signalements.region'),
        ),
        migrations.AddField(
            model_name='centreetatcivil',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centres', to='signalements.region'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('nom', 'region')},
        ),
        migrations.AddIndex(
            model_name='centreetatcivil',
            index=models.Index(fields=['region', 'commune'], name='signalement_region__001fae_idx'),
        ),
    ]
