# Generated by Django 6.0.6 on 2026-06-17 18:08

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyseia',
            old_name='donnees_extraites',
            new_name='extracted_data',
        ),
        migrations.RenameField(
            model_name='analyseia',
            old_name='score_fraude',
            new_name='fraud_score',
        ),
        migrations.RenameField(
            model_name='analyseia',
            old_name='modele_utilise',
            new_name='model_used',
        ),
        migrations.RenameField(
            model_name='analyseia',
            old_name='texte_ocr',
            new_name='ocr_text',
        ),
        migrations.RenameField(
            model_name='analyseia',
            old_name='score_doublon',
            new_name='similarity_score',
        ),
        migrations.RemoveField(
            model_name='analyseia',
            name='niveau_risque',
        ),
        migrations.AddField(
            model_name='analyseia',
            name='decision',
            field=models.CharField(choices=[('VALID', 'Valid'), ('SUSPECT', 'Suspect'), ('FRAUD', 'Fraud')], default=datetime.datetime(2026, 6, 17, 18, 8, 33, 120226, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyseia',
            name='matched_acte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='signalements.acteetatcivil'),
        ),
        migrations.AddField(
            model_name='analyseia',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default=datetime.datetime(2026, 6, 17, 18, 8, 37, 77253, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyseia',
            name='acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalements.acteetatcivil'),
        ),
        migrations.CreateModel(
            name='FileSynchronisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donnees', models.JSONField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SYNCHRONISE', 'Synchronisé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('synchronise_le', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_synchronisation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['statut'], name='signalement_statut_0d60c6_idx'), models.Index(fields=['cree_le'], name='signalement_cree_le_6d0a3f_idx')],
            },
        ),
    ]
