# Generated by Django 6.0.6 on 2026-06-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteetatcivil',
            name='type_acte',
            field=models.CharField(choices=[('NAISSANCE', 'Naissance'), ('MARIAGE', 'Mariage'), ('DECES', 'Décès'), ('CIN', "Carte d'identité"), ('PASSEPORT', 'Passeport'), ('PERMIS_CONDUIRE', 'Permis de conduire'), ('CASIER_JUDICIAIRE', 'Casier Judiciaire'), ('TITRE_SEJOUR', 'Titre de séjour')], max_length=20),
        ),
    ]
