# Generated by Django 6.0.6 on 2026-06-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0003_rename_donnees_extraites_analyseia_extracted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseia',
            name='decision',
            field=models.CharField(choices=[('VALID', 'Valid'), ('SUSPECT', 'Suspect'), ('FRAUD', 'Fraud')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analyseia',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='centreetatcivil',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='filesynchronisation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SYNCHRONISE', 'Synchronisé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20),
        ),
    ]
