# Generated by Django 6.0.6 on 2026-06-18 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0003_rename_donnees_extraites_analyseia_extracted_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreEtatCivil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_identification', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('type_acte', models.CharField(choices=[('NAISSANCE', 'Naissance'), ('MARIAGE', 'Mariage'), ('DECES', 'Décès')], default='NAISSANCE', max_length=20)),
                ('numero_acte_officiel', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registre_entries', to='signalements.centreetatcivil')),
            ],
            options={
                'verbose_name': 'Registre état civil',
                'verbose_name_plural': 'Registre état civil',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analyseia',
            name='matched_registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='signalements.registreetatcivil'),
        ),
    ]
